### ISSUE TITLE
Problems in drawing the screen

### ISSUE THREAD

**Issue by euglevi** [DreamMaoMao/keyjump.yazi#12]
Thank you for the nice plugin! I think this improves yazi substantially.

I think I spotted a bug. When I use yazi in 1/4 of the screen, the plugin works well (I use the keep mode).

![24_02_12_12_10_04](https://github.com/DreamMaoMao/keyjump.yazi/assets/58224469/220ebd9b-9422-4a8a-9492-4d990e130709)

When I use it in half the screen or in full screen, I then see nothing.

![24_02_12_12_01_52](https://github.com/DreamMaoMao/keyjump.yazi/assets/58224469/414b9020-3b82-43fe-8a9c-61079c731d13)

If I press Esc, it restores the usual screen.

![24_02_12_12_02_02](https://github.com/DreamMaoMao/keyjump.yazi/assets/58224469/a45df9e6-53aa-4c29-8f56-c5dfa72ff77f)

What is responsible for this issue? I have the latest stable version of Yazi (but I also tried with the git branch) and of the plugin.

**Comment by DreamMaoMao** [comment]
oh~   i konw what happen.  

Because the current  jump key generation supports a maximum of 48 items your screen is too large for this limit


Let me think how do we solve this problem

**Comment by euglevi** [comment]
Would doubling the keys solve the issue?

**Comment by DreamMaoMao** [comment]
Oh no if you're using normal mode instead of global mode maybe I have an optimization

**Comment by DreamMaoMao** [comment]
try latest commit . it you use normal mode , it will perfer solved you problem.

**Comment by euglevi** [comment]
I confirm that the problem is solved! Thank you, and that was super fast!
