### ISSUE TITLE
Plugin doesn't work and can't refresh  the screen in yazi 0.2.4

### ISSUE THREAD

**Issue by chasing-freedom** [DreamMaoMao/keyjump.yazi#16]
https://github.com/DreamMaoMao/keyjump.yazi/assets/48324431/0dfb446d-edb5-44a3-b6d8-f8f775ff65f9

I bind key `i` to `Keep mode`. The plugin doesn't work and can't refresh the screen. The  navigation  characters  doesn't disappear until I press `i` again.

**Environment**

`kepmap.toml` setting
```
[[manager.prepend_keymap]]
on = ["i"]
run = "plugin keyjump --sync --args=keep"
desc = "Keyjump (Keep mode)"
```

OS :  `Archlinux`
Kernel : `6.7.9-zen1-1-zen`
Desktop Environment: `hyprland 0.35.0-2`
Terminal: `kitty 0.31.0`
Yazi version: `yazi 0.2.4 (Arch Linux 2024-03-10)`
Keyjump.yazi version: the newest commit

**Comment by DreamMaoMao** [comment]
That doesn't seem to be a problem to me. Does the other modes work?

**Comment by DreamMaoMao** [comment]
[[manager.prepend_keymap]]
on = ["i"]
exec = "plugin keyjump --sync --args=keep"
desc = "Keyjump (Keep mode)"

try chagr `run` to `exec`

**Comment by DreamMaoMao** [comment]
could you show me you log file? in this path

~/.local/state/yazi/yazi.log

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/keyjump.yazi/assets/30348075/3ccbbd90-c288-40fc-84ec-211750fe3ea8

**Comment by chasing-freedom** [comment]
> That doesn't seem to be a problem to me. Does the other modes work?

work:  `Normal mode` `Global mode`
doesn't work : `Keep mode` `Select mode`

**Comment by DreamMaoMao** [comment]
PS: I add DE field in Environment description.

what is this mean?

**Comment by chasing-freedom** [comment]
> PS: I add DE field in Environment description.
> 
> what is this mean?

Noting. I just add the  `Desktop Environment: hyprland 0.35.0-2` into Environment section of the first comment.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/keyjump.yazi/assets/30348075/a1e9ab93-4534-48a9-be88-f64a5f703c61)
i know what happen to you.

you add the --sync in args.  but this has be remove. see the latest readme.

![image](https://github.com/DreamMaoMao/keyjump.yazi/assets/30348075/bae9b1aa-01de-44bb-8944-90c103917600)

**Comment by chasing-freedom** [comment]
> ![image](https://private-user-images.githubusercontent.com/30348075/312092998-a1e9ab93-4534-48a9-be88-f64a5f703c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTAzNzksIm5iZiI6MTcxMDI1MDA3OSwicGF0aCI6Ii8zMDM0ODA3NS8zMTIwOTI5OTgtYTFlOWFiOTMtNDUzNC00OGE5LWJlODgtZjY0YTVmNzAzYzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDEzMjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MjY0MjZhN2FiMGUyZjg2N2NlNzgwMjA4ZjA0MDVlYWU5YWY0MmM3NzIwNjYzNzNjNGUxYTJiYWQwZmM5MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cxeimPejvG0wMP474HF1DVOqRrAHuII8eY_9OujFNcw) i know what happen to you.
> 
> you add the --sync in args. but this has be remove. see the latest readme.
> 
> ![image](https://private-user-images.githubusercontent.com/30348075/312093616-bae9b1aa-01de-44bb-8944-90c103917600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNTAzNzksIm5iZiI6MTcxMDI1MDA3OSwicGF0aCI6Ii8zMDM0ODA3NS8zMTIwOTM2MTYtYmFlOWIxYWEtMDFkZS00NGJiLTg5NDQtOTBjMTAzOTE3NjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDEzMjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZjI0NmQzNWFhMDEyOTRiMWQ4NmFjYjExZTRiMmJjMGFmOTA3MTljMWYxMDliNjFmNjMzZjJhNjJjOTBmNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iTb_zLV1vAWwrvjwpquonvv_lZyQ_D3M_N5hGj6q51E)

It works. Thank for your help.
