### ISSUE TITLE
Use "global once" mode with "auto enter"

### ISSUE THREAD

**Issue by shauryagoel** [DreamMaoMao/keyjump.yazi#17]
I want to use global once mode and enter into a directory just like keep mode has it. Is it possible to achieve currently?

**Comment by DreamMaoMao** [comment]
I tried it out and it's a pretty weird using logic. i dont think this is a good idea sorry.

**Comment by DreamMaoMao** [comment]
I tried it out and it's a pretty weird using logic. i dont think this is a good idea sorry.
