### ISSUE TITLE
something doesn't  work when there are spaces in the file name in windows

### ISSUE THREAD

**Issue by DreamMaoMao** [DreamMaoMao/keyjump.yazi#6]
![image](https://github.com/DreamMaoMao/keyjump.yazi/assets/30348075/8bb95b64-5ae6-4e92-b738-7bc06eb1bb63)

**Comment by sxyazi** [comment]
Should be fixed in https://github.com/DreamMaoMao/keyjump.yazi/pull/5

**Comment by DreamMaoMao** [comment]
@sxyazi   Okay, it seems to have nothing to do with the spaces in the folder, but this problem occurs in some folders. I want to test what they have in common.

**Comment by DreamMaoMao** [comment]
fine, I discovered the pattern. If the current folder is the next-level folder of a Chinese folder, then there will be this error.

![image](https://github.com/DreamMaoMao/keyjump.yazi/assets/30348075/78a188fd-fc58-496c-b3e6-91dd2433c454)

**Comment by DreamMaoMao** [comment]
may be something wrong in this:
![image](https://github.com/DreamMaoMao/keyjump.yazi/assets/30348075/d495a1ff-2909-4ae8-86e0-8597d192356a)

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/keyjump.yazi/assets/30348075/ccffb3fe-75ff-4847-af6d-22dbe55cad71)
This kind of link directory also has this problem

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/keyjump.yazi/assets/30348075/8f28e087-57bd-4f4f-a91c-d4029754b780)
![image](https://github.com/DreamMaoMao/keyjump.yazi/assets/30348075/4a3bdd22-aaf1-4b20-b98a-ef7b14b7b06a)


But this problem disappears if I don't use /b parameter

**Comment by DreamMaoMao** [comment]
> ![image](https://private-user-images.githubusercontent.com/30348075/302497744-ccffb3fe-75ff-4847-af6d-22dbe55cad71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxOTMwMTQsIm5iZiI6MTcwNzE5MjcxNCwicGF0aCI6Ii8zMDM0ODA3NS8zMDI0OTc3NDQtY2NmZmIzZmUtNzVmZi00ODQ3LWFmNmQtMjJkYmU1NWNhZDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA0MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OWJmMzZjMGZjMWQzOTkyNjMxZTlkY2IwMjQ3YjM3YjllOTVjNGRhZWRhNDJjYzY1MGJiNjMwZWRiNTNmMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ECWhooTD7EGdGMYQxPUJZWYHw2-VU9TB87g_99gAj68) This kind of link directory also has this problem

this proble also disappear without /b

**Comment by DreamMaoMao** [comment]
@PaysanCorrezien 


Do you  must use the /b parameter in your environment?

**Comment by DreamMaoMao** [comment]
Although the implementation doesn't look very good, now it works well when I tested it under win and linux.

https://github.com/DreamMaoMao/keyjump.yazi/commit/03be5988dfc27f7f2a803bb17edc164cb4b5a2c5

**Comment by DreamMaoMao** [comment]
It seems to be a problem with win-terminal. I can use the /b parameter after switching to wezterm.
